function [paths] = get_beamformer_paths(spacing, contrast, h_freq, ...
                                        l_freq, input, output, reg, ...
                                        weight_norm, channel_type, ...
                                        tmin, tmax, ISI_type)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

subpaths = {'stcs/common_filter/' 'stcs/common_filter/' ...
            'stcs/common_filter/contrasts/' ...
            'itcs/common_filter/' 'itcs/common_filter/' ...
            'itcs/common_filter/contrasts/'};
n_subpaths = length(subpaths);

spacing_condition_1 = [contrast{1} '_' spacing '_mm_common_filter_' ...
                       contrast{1} '_' contrast{2} '_'];
spacing_condition_2 = [contrast{2} '_' spacing '_mm_common_filter_' ...
                       contrast{1} '_' contrast{2} '_'];
spacing_contrast    = [contrast{1} '_' contrast{2} '_contrast_' spacing ...
                       '_mm_'];
                   
paths = cell(2, 6);                   

for subpath_index = 1:n_subpaths
    
    prepend = [ISI_type '_ISI_' channel_type '_reg_' reg '_weight_' ...
               weight_norm '_'];
    postpend = ['hp_' h_freq '_Hz_lp_' l_freq '_Hz_' ...
                num2str(tmin * 1e3) '_ms_to_' num2str(tmax * 1e3) '_ms_'];
    if mod(subpath_index, 3) == 1
        paths{1, subpath_index} = [subpaths{subpath_index} prepend ...
                                   spacing_condition_1 postpend ...
                                   input];
        paths{2, subpath_index} = [subpaths{subpath_index} prepend ...
                                   spacing_condition_1 postpend ...
                                   output];
    elseif mod(subpath_index, 3) == 2
        paths{1, subpath_index} = [subpaths{subpath_index} prepend ...
                                   spacing_condition_2 postpend ...
                                   input];
        paths{2, subpath_index} = [subpaths{subpath_index} prepend ...
                                   spacing_condition_2 postpend ...
                                   output];
    elseif mod(subpath_index, 3) == 0
        paths{1, subpath_index} = [subpaths{subpath_index} prepend ...
                                   spacing_contrast postpend ...
                                   input];
        paths{2, subpath_index} = [subpaths{subpath_index} prepend ...
                                   spacing_contrast postpend ...
                                   output];
    end
    

end

