Executing following command on 1 threads:
./subject_0020.sh

mne_surf2bem version 1.6 compiled at Dec 21 2009 19:47:09

input  file #   1 : /projects/MINDLAB2019_MEG-CerebellarClock/scratch/tactile_jitter/freesurfer/0020/surf/lh.seghead / id = 4 / sigma N/A
output file       : /projects/MINDLAB2019_MEG-CerebellarClock/scratch/tactile_jitter/freesurfer/0020/bem/0020-head-dense.fif

New quad file : nvert = 252842 nquad = 253761
	Triangle and vertex normals and neighboring triangles...[done]
	Vertex neighbors...Too many neighbors for vertex 129146.
Done executing
