Executing following command on 1 threads:
./subject_0002.sh
./subject_0002.sh: line 1: !/bin/bash: No such file or directory
./subject_0002.sh: line 2: $: command not found
./subject_0002.sh: line 4: Make: command not found
./subject_0002.sh: line 6: Change: command not found
./subject_0002.sh: line 8: Run: command not found
./make_scalp_surfaces.sh: line 2: syntax error near unexpected token `{}'
./make_scalp_surfaces.sh: line 2: `make_scalp_surfaces () {}'
Done executing
